columnSuffix: null
contentColumnType: string
fieldGroup: b018bde8-26d8-4dd0-9acb-629428ba416d # Common
handle: results
instructions: ''
name: Results
searchable: false
settings:
  columns:
    __assoc__:
      -
        - f93dbbd5-17a7-4907-be0b-9e0c03afc5a2 # User Id
        -
          __assoc__:
            -
              - width
              - ''
      -
        - fbf27b47-374b-4b3b-acd0-3c24a7c8f93c # User Data
        -
          __assoc__:
            -
              - width
              - ''
  contentTable: '{{%stc_results}}'
  fieldLayout: row
  maxRows: ''
  minRows: ''
  placeholderKey: null
  propagationMethod: all
  selectionLabel: ''
  staticField: '1'
translationKeyFormat: null
translationMethod: site
type: verbb\supertable\fields\SuperTableField
